version: "3.9"
services:
  postgres:
    container_name: ecommerce-db
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ecommerce

