version: "3.9"
services:
  postgres:
    container_name: ecommerce-db
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ecommerce
  greenmail:
    image: greenmail/standalone:2.0.0
    environment:
      - GREENMAIL_USER=test
      - GREENMAIL_PASSWORD=test
    ports:
      - 3025:3025
      - 3110:3110
      - 3143:3143

