spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/ecommerce
  jpa:
    show-sql: true
  mail:
    password: test
    username: test
    host: 127.0.0.1
    port: 3025 # default protocol port + 3000 as offset
    protocol: smtp
    test-connection: false # avoid setting this to true when using a per-test-method GreenMail server

server:
  error:
    include-stacktrace: on_param

custom:
  stacktrace.trace: true
  application.domain: http://localhost:8080
  account.activation.endpoint: /auth/activate-account
