spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

custom:
  stacktrace.trace: false

