spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/ecommerce
  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: on_param

custom:
  stacktrace.trace: true
  application.domain: http://http://localhost:8080
  account.activation.endpoint: /auth/activate
